name:                metar-decoder
version:             0.1.0.0
github:              "SkamDart/metar-decoder"
license:             BSD3
author:              "Cameron Dart"
maintainer:          "cdart2@gmail.com"
copyright:           "2019 Cameron Dart"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/SkamDart/metar-decoder#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  metar-decoder-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - metar-decoder

tests:
  metar-decoder-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - metar-decoder
